package com.devsoto.monical.ui.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import com.devsoto.monical.R

/**
 * Monical design tokens — "toda la app es un ticket de compra siendo armado".
 *
 * Ported from the design prototype. Accent (Terracota) and the mono font are fixed: the
 * prototype's live Tweaks switcher was intentionally dropped.
 */
object Moni {
    // Surface the phone sits the receipt on (a desk / counter)
    val desk = Color(0xFFD6CDBA)
    val deskHi = Color(0xFFE0D8C7)

    // Thermal paper
    val paper = Color(0xFFF5EEDE)
    val paperHi = Color(0xFFFBF6EA)
    val paperEdge = Color(0xFFECE2CD)

    // Ink (slightly faded thermal print)
    val ink = Color(0xFF2C2720)
    val inkSoft = Color(0xFF857A66)
    val inkFaint = Color(0xFFB4A98E)
    val rule = Color(0xFFC2B696) // dashed separators

    // "Devuelto / pagado" — muted ink green
    val paid = Color(0xFF4E7A50)
    val paidWash = Color(0xFFE0E7D6)

    // Accent — Terracota stamp ink (fixed)
    val accent = Color(0xFFC2532E)
    val accentDark = Color(0xFF9C3E1C)
    val accentSoft = Color(0xFFE9CDBC)
    val accentWash = Color(0xFFF1DBCB)

    /** Monospace family used across the whole UI. */
    val font: FontFamily = FontMono
}

/**
 * Body font: the platform monospace family, for a robust, network-free build that still gives
 * the thermal-receipt look.
 *
 * To use *Spline Sans Mono* (the prototype's choice) instead, add the dependency
 * `androidx.compose.ui:ui-text-google-fonts` (already declared) plus
 * `res/values/font_certs.xml` with the standard `com_google_android_gms_fonts_certs` array
 * (generated by Android Studio for Downloadable Fonts), then build the family from a
 * `GoogleFont.Provider`. Alternatively bundle the `.ttf` under `res/font`.
 */
val FontMono: FontFamily = FontFamily(
    Font(resId = R.font.spline_sans_mono_regular, weight = FontWeight.Normal),
            Font(resId = R.font.spline_sans_mono_bold, weight = FontWeight.Bold),
            Font(resId = R.font.spline_sans_mono_medium, weight = FontWeight.Medium)
)

/** Physical calculator keycaps (Helvetica → platform sans). */
val FontKey: FontFamily = FontFamily.SansSerif
